/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proveedor;

import controlador.Ctrl_Proveedor;
import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Proveedor;

/**
 *
 * @author Gregorio
 */
public class DialogModificar extends javax.swing.JDialog {

    private int idProveedor;
    private String nombreAnt;

    public DialogModificar(Frame owner, boolean modal) {
        super(owner, modal);
    }

    public DialogModificar(java.awt.Frame parent, boolean modal, Proveedor proveedor) {
        super(parent, modal);
        initComponents();
        this.setSize(new Dimension(506, 372));
        this.setTitle("Modificar Proveedor");

        setIconImage(new ImageIcon(getClass().getResource("../../img/ventas.png")).getImage());

        this.idProveedor = proveedor.getIdProveedor();
        txt_nombre1.setText(proveedor.getDescripcion());
        txt_nombre.setText(proveedor.getDireccion());
        jRadioButton1.setSelected(proveedor.getEstado() == 1 ? true : false);

        this.nombreAnt = txt_nombre1.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nombre1 = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombre1KeyPressed(evt);
            }
        });
        getContentPane().add(txt_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 80, 340, 30));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 135, 340, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-guardar-50.png"))); // NOI18N
        jButton2.setText("Agregar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 265, 171, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salir-50.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 265, 171, 51));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 189, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_modificar_proveedor.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombre1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txt_nombre.requestFocus();
        }
    }//GEN-LAST:event_txt_nombre1KeyPressed

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jButton2.doClick();
        }
    }//GEN-LAST:event_txt_nombreKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (!txt_nombre.getText().isEmpty() && !txt_nombre1.getText().isEmpty()) {

            Proveedor proveedor = new Proveedor();
            Ctrl_Proveedor ctrlProveedor = new Ctrl_Proveedor();

            if (!nombreAnt.equals(txt_nombre1.getText().trim())) {
                if (ctrlProveedor.existeProveedor(txt_nombre1.getText().trim()) == true) {
                    JOptionPane.showMessageDialog(null, "Ya existe un Proveedor con ese nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            proveedor.setIdProveedor(idProveedor);
            proveedor.setDescripcion(txt_nombre1.getText().trim());
            proveedor.setDireccion(txt_nombre.getText().trim());
            proveedor.setEstado(jRadioButton1.isSelected() ? 1 : 0);

            if (ctrlProveedor.actualizarProveedor(proveedor) == true) {
                JOptionPane.showMessageDialog(null, "Proveedor modificado.", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el Proveedor.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Complete los datos del Proveedor.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModificar dialog = new DialogModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    // End of variables declaration//GEN-END:variables
}
